### ISSUE TITLE
Could you provide the Mirror.txt file?

### ISSUE THREAD

**Issue by caicai-liu** [Dixin-Lab/generalized-face-landmarker#2]
Thank you.I would like to know if the train_list.txt for 300W mentioned in the code corresponds to the provided 300W_frontal_train_list.txt. If so, my directory structure is the same as the one you provided, but when training, Combine_new.py throws the following error:
---------start training landmarker----------
/data4/ls/generalized-face-landmarker-master/generalized-face-landmarker-master/data/Combine_new.py:27: UserWarning: genfromtxt: Empty input file: "Dataset/300W/Mirror.txt"
  self.flip_index = np.genfromtxt(os.path.join(self.src_root, "Mirror.txt"), dtype=int,
Traceback (most recent call last):
  File "/data4/ls/generalized-face-landmarker-master/generalized-face-landmarker-master/train.py", line 243, in <module>
    train(warpA2B, W_optim, L_optim, opt)
  File "/data4/ls/generalized-face-landmarker-master/generalized-face-landmarker-master/train.py", line 98, in train
    train_combine_loader, test_combine_loader = get_combine_dataloader(opt, save_path)
  File "/data4/ls/generalized-face-landmarker-master/generalized-face-landmarker-master/data/Combine_new.py", line 241, in get_combine_dataloader
    train_dataset = Combine_Dataset(cfg=cfg, opt=opt, is_train=True, transform=normalize, pseudo_label_path=save_path)
  File "/data4/ls/generalized-face-landmarker-master/generalized-face-landmarker-master/data/Combine_new.py", line 55, in __init__
    self.database = self.get_file_information()
  File "/data4/ls/generalized-face-landmarker-master/generalized-face-landmarker-master/data/Combine_new.py", line 69, in get_file_information
    Points = np.genfromtxt(temp_name[:-3] + 'pts', skip_header=3, skip_footer=1, delimiter=' ') - 1.0
  File "/data4/ls/anaconda3/envs/landmark/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 2007, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/data4/ls/anaconda3/envs/landmark/lib/python3.10/site-packages/numpy/lib/_datasource.py", line 192, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/data4/ls/anaconda3/envs/landmark/lib/python3.10/site-packages/numpy/lib/_datasource.py", line 529, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: Dataset/300W/100032540_1.pts not found.
What is the reason for this? Thank you for your answer.

**Comment by plustwo0** [comment]
In summary, there're two main issues with the reproduction:

1. Sorry for the oversight, the download link in README did not include `Mirror.txt`.
You can download it from [Google Drive](https://drive.google.com/file/d/1MnTvZolh2CaDbqIsneWQWuik1i7aC2Vt/view?usp=drive_link). Thanks for the correction!

2. It seems to be a problem with `train_list.txt`, try [this](https://drive.google.com/file/d/1vEjeIbCSSKy8T8O-5O0-e3mGf9Fvsz0b/view?usp=drive_link) out. This `train_list.txt` will indicate the sub-dataset each image belongs to.

Thanks for your interest in our work! Feel free to contact if you have any questions XD
